name: cli_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  uuid: ^4.4.2
  parking_cli_shared:
    path: '../parking_cli_shared'
  http: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

  
